In [2]:
import pandas as pd

In [24]:
real_time_clusters = pd.read_parquet('real-time clusters/20230101-20240101_real_time_clusters.parquet')

In [31]:
real_time_clusters

,alarm_id,network,ne_type,first_occurrence,last_update,data,ne_id,geo_code,min_cluster_first_occurrence,domain,link_cluster,cluster_id,cluster_id2
0,EFM;63af9dfe2aaf2c000125807a,an,lnbts,2022-12-31 03:27:10,2022-12-31 23:59:01,2023-01-01 00:00:02,1btste08d,alad,2022-12-31 03:27:10,mob,None,202301010000_3,202301010000_1
1,EFM;63af9dfec623b40001a5c9cf,an,lnbts,2022-12-31 03:27:10,2022-12-31 23:58:55,2023-01-01 00:00:02,1btste08d,alad,2022-12-31 03:27:10,mob,None,202301010000_3,202301010000_1
2,COS1P;136902468,sdh,ad16,2022-12-31 22:19:34,2022-12-31 23:58:46,2023-01-01 00:00:02,alesitaj/ad16/73,ales,2022-12-31 22:19:34,tx,None,202301010000_20,202301010000_2
3,EFM;63b0beaf2aaf2c0001258736,an,lebts,2022-12-31 23:58:55,2022-12-31 23:59:27,2023-01-01 00:00:02,5btsle119,alss,2022-12-31 23:58:55,mob,None,202301010000_9,202301010000_3
4,COS1P;136891403,sdh,oadm,2022-12-31 11:26:16,2022-12-31 23:59:52,2023-01-01 00:00:02,ancoitab/oadm/1,anco,2022-12-31 11:26:16,tx,None,202301010000_21,202301010000_4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38,EFMTX;6591efb9d7d6bc00019444d8,adsl,adsl,2023-12-31 23:48:25,2023-12-31 23:56:43,2023-12-31 23:58:02,taglitac/adsl/1,tagl,2023-12-31 23:48:24,tx,None,202312312350_16,202312312350_13
39,EFMTX;6591f046d8beb800016deaef,ptn,ptn3,2023-12-31 23:50:46,2023-12-31 23:57:34,2023-12-31 23:58:02,thesitae/ptn3/1,thes,2023-12-31 23:44:44,tx,None,202312312348_17,202312312344_9
40,EFM;6591f199d4c961000177739d,an,lnbts,2023-12-31 23:56:25,2023-12-31 23:56:37,2023-12-31 23:58:03,1btsts059,trie,2023-12-31 23:56:25,mob,None,202312312358_1,202312312358_13
41,EFM;6591f19aba09b0000160c08d,an,lnbts,2023-12-31 23:56:26,2023-12-31 23:57:59,2023-12-31 23:58:03,1btsts059,trie,2023-12-31 23:56:25,mob,None,202312312358_1,202312312358_13
42,EFMTX;6591ef19d7d6bc000194445c,sdh,prhu,2023-12-31 23:45:45,2023-12-31 23:57:22,2023-12-31 23:58:02,viarital/prhu/4,viar,2023-12-31 23:45:45,tx,None,202312312358_28,202312312358_14

## TEST mob

In [3]:
mob = pd.read_parquet("alarms datasets/mob/20230101-20240101_inpas_mob_preprocess__an__last_event__last_event__ext1.parquet")

In [4]:
mob.columns

Index(['alarm_id', 'data', 'first_occurrence', 'first_severity',
       'last_occurrence', 'last_update', 'loc_descr', 'make_prediction',
       'ne_id', 'network', 'severity', 'std_probable_cause_no',
       'correlation_role', 'corr_intra', 'data_presentazione',
       'delay_expire_time', 'is_correlated', 'is_root_cause', 'mob_cat_sito',
       'mob_key_type', 'num_figli', 'outage', 'park', 'tt_correlation_state',
       'to_operation_view', 'tt_request_status', 'wr_status', 'alarm_count',
       'category', 'cx_auton_batterie', 'em', 'loc_group', 'manager',
       'manufacturer', 'mob_slogan', 'ne_type', 'origine_guasto',
       'strategicita', 'subnetwork', 'alarm_duration',
       'first_occurrence_time_of_week', 'first_occurrence_day_of_week',
       'first_occurrence_hour', 'province', 'loc_descr_cat', 'province_cat',
       'is_note_present', 'is_ack_or_notes', 'is_tt', 'is_abam_tt', 'loc_name',
       'tt_id', 'link_id', 'loc_name_a', 'loc_name_z', 'lp_id', 'lp_type'],
      dtype='object')

In [5]:
mob = mob[['alarm_id', 'std_probable_cause_no']]

In [6]:
# Trova le righe in cui 'std_probable_cause_no' Ã¨ null
rows_with_null = mob[mob['std_probable_cause_no'].isnull()]
rows_with_null

                              alarm_id std_probable_cause_no
2284      EFM;63b06997c623b40001a66cf1                   NaN
6419      EFM;63b0e4aa9603570001f41498                   NaN
12285     EFM;63b117909603570001f4372a                   NaN
12290     EFM;63b1178b9603570001f43724                   NaN
17284     EFM;63b12cc0c623b40001a6bf18                   NaN
...                                ...                   ...
27962474  EFM;658d4142ce826000012d2c26                   NaN
28099740  EFM;6565252885384b0001beb7ed                   NaN
28099741  EFM;6565252945a8dc0001a5a5fc                   NaN
28099742  EFM;6565252a45a8dc0001a5a5fe                   NaN
28166990  EFM;658c38cdbbe75c00017d6001                   NaN

[24983 rows x 2 columns]

## Test SDH

In [7]:
sdh = pd.read_parquet("alarms datasets/tx/20230101-20240101_inpas_tx_preprocess__sdh__last_event__last_event__ext1.parquet")

In [8]:
sdh.columns

Index(['alarm_id', 'data', 'first_occurrence', 'first_severity',
       'last_occurrence', 'last_update', 'loc_name', 'make_prediction',
       'ne_id', 'network', 'severity', 'std_probable_cause_no', 'summary',
       'correlation_role', 'corr_intra', 'data_presentazione',
       'delay_expire_time', 'is_correlated', 'is_root_cause', 'num_figli',
       'outage', 'park', 'to_operation_view', 'tt_correlation_state',
       'tt_request_status', 'wr_status', 'alarm_count', 'alarm_type',
       'category', 'cx_auton_batterie', 'em', 'loc_group', 'manager',
       'manufacturer', 'ne_type', 'origine_guasto', 'strategicita',
       'subnetwork', 'tx_flag_protezione', 'alarm_duration',
       'first_occurrence_time_of_week', 'first_occurrence_day_of_week',
       'first_occurrence_hour', 'ne_id0', 'ne_id1', 'ne_id2', 'ne_id3',
       'ne_id_group', 'ne_id_area', 'ne_id_area2', 'is_note_present',
       'is_ack_or_notes', 'is_tt', 'is_abam_tt', 'tt_id', 'link_id',
       'link_type', 'loc_name_a', 'loc_name_z', 'lp_id', 'lp_type'],
      dtype='object')

In [9]:
sdh = sdh[['alarm_id', 'std_probable_cause_no']]

In [10]:
# Trova le righe in cui 'std_probable_cause_no' Ã¨ null
rows_with_null = sdh[sdh['std_probable_cause_no'].isnull()]
rows_with_null

                                alarm_id std_probable_cause_no
12906                    COS1P;136637285                   NaN
15638                    COS1P;136629818                   NaN
23889                    COS1P;136633717                   NaN
24525                    COS1P;136911221                   NaN
35649                    COS1P;136633999                   NaN
...                                  ...                   ...
11248697  EFMTX;65895878c3980b0001252678                   NaN
11248777  EFMTX;6591f1c31d392e0001f95685                   NaN
11248882  EFMTX;6591b3bf1d392e0001f8f58e                   NaN
11248893  EFMTX;6591f085e294c600010bf21c                   NaN
11248895  EFMTX;6591f2169c84570001bd4334                   NaN

[14506 rows x 2 columns]

## Test PTN

In [11]:
ptn = pd.read_parquet("alarms datasets/tx/20230101-20240101_inpas_tx_preprocess__ptn__last_event__last_event__ext1.parquet")

In [12]:
ptn = ptn[['alarm_id', 'std_probable_cause_no']]

In [13]:
# Trova le righe in cui 'std_probable_cause_no' Ã¨ null
rows_with_null = ptn[ptn['std_probable_cause_no'].isnull()]
rows_with_null

                              alarm_id std_probable_cause_no
1876                   COS1P;136211827                   NaN
23748                  COS1P;137881044                   NaN
36626                  COS1P;138461758                   NaN
70607                  COS1P;140119254                   NaN
74938                  COS1P;140263040                   NaN
...                                ...                   ...
407820  EFMTX;65911bf69c84570001bccc5d                   NaN
408699  EFMTX;6591f0c3e294c600010bf253                   NaN
408715  EFMTX;6591f0f87003ea0001c6ffe1                   NaN
408721  EFMTX;6591f157e294c600010bf2f8                   NaN
408741  EFMTX;6591f1a6e294c600010bf31c                   NaN

[438 rows x 2 columns]

## Test ADSL

In [14]:
adsl = pd.read_parquet("alarms datasets/tx/20230101-20240101_inpas_tx_preprocess__adsl__last_event__last_event__ext1.parquet")

In [15]:
adsl = adsl[['alarm_id', 'std_probable_cause_no']]

In [16]:
# Trova le righe in cui 'std_probable_cause_no' Ã¨ null
rows_with_null = adsl[adsl['std_probable_cause_no'].isnull()]
rows_with_null

                               alarm_id std_probable_cause_no
9233                     COS4P;86675919                   NaN
10844                    COS4P;86734510                   NaN
11347                    COS4P;86651430                   NaN
11790                    COS4P;86651432                   NaN
12184                    COS4P;86734935                   NaN
...                                 ...                   ...
9326626  EFMTX;6591f0f37003ea0001c6ffde                   NaN
9326689  EFMTX;6591f2290d1c1f0001da3871                   NaN
9326826  EFMTX;6591f24101021b00010facc3                   NaN
9326827  EFMTX;6591f241ad7bae0001862007                   NaN
9326832  EFMTX;6591f24101021b00010facc4                   NaN

[23413 rows x 2 columns]

## Test PDH

In [17]:
pdh = pd.read_parquet("alarms datasets/tx/20230101-20240101_inpas_tx_preprocess__pdh__last_event__last_event__ext1.parquet")

In [18]:
pdh = pdh[['alarm_id', 'std_probable_cause_no']]

In [19]:
# Trova le righe in cui 'std_probable_cause_no' Ã¨ null
rows_with_null = pdh[pdh['std_probable_cause_no'].isnull()]
rows_with_null

                              alarm_id std_probable_cause_no
2773                    COS3P;66409151                   NaN
3321                    COS3P;66412592                   NaN
49222                   COS3P;66875006                   NaN
53458                   COS3P;66411320                   NaN
104080                  COS3P;67276248                   NaN
...                                ...                   ...
803606  EFMTX;6590cec5d8beb800016cd7b0                   NaN
805794  EFMTX;6591f1b5975f5100015a48b4                   NaN
805795  EFMTX;6591f1b8a7e2aa000108da75                   NaN
805796  EFMTX;6591f1b6975f5100015a48b8                   NaN
805806  EFMTX;6591f1f1975f5100015a48d3                   NaN

[613 rows x 2 columns]

In [20]:
mob = mob.rename(columns={'std_probable_cause_no': 'slogan'})
adsl = adsl.rename(columns={'std_probable_cause_no': 'slogan'})
sdh = sdh.rename(columns={'std_probable_cause_no': 'slogan'})
ptn = ptn.rename(columns={'std_probable_cause_no': 'slogan'})
pdh = pdh.rename(columns={'std_probable_cause_no': 'slogan'})

In [21]:
total_alarms = pd.concat([mob, sdh, ptn, adsl, pdh])

In [25]:
total_alarms

                              alarm_id                                 slogan
0         EFM;63b098b01a65d200011620f8  slot group ul antenna isolation alarm
1         EFM;63b0b476c623b40001a68b45         received bit error ratio ber e
2         EFM;63b0b5a8c623b40001a68b9b         received bit error ratio ber e
3         EFM;63b0b5c6c623b40001a68ba2         received bit error ratio ber e
4         EFM;63b0b675c623b40001a68c03         received bit error ratio ber e
...                                ...                                    ...
805948  EFMTX;6483fbf332d3d9000193e3a2                 fama no alarm since hh
805949  EFMTX;64c92bbe008e1d0001c7ff49                  offline sw fama nport
805950  EFMTX;65661efc590d4500011934d1                 fama no alarm since hh
805951  EFMTX;6591f1b6975f5100015a48b6                        signal degraded
805952  EFMTX;658f5efad7d6bc0001921429                   ser guasto della ser

[49966959 rows x 2 columns]

In [35]:
cluster_filtered = real_time_clusters[["alarm_id", "cluster_id2","ne_id","domain"]]

In [36]:
cluster_filtered

                          alarm_id      cluster_id2             ne_id domain
0     EFM;63af9dfe2aaf2c000125807a   202301010000_1         1btste08d    mob
1     EFM;63af9dfec623b40001a5c9cf   202301010000_1         1btste08d    mob
2                  COS1P;136902468   202301010000_2  alesitaj/ad16/73     tx
3     EFM;63b0beaf2aaf2c0001258736   202301010000_3         5btsle119    mob
4                  COS1P;136891403   202301010000_4   ancoitab/oadm/1     tx
..                             ...              ...               ...    ...
38  EFMTX;6591efb9d7d6bc00019444d8  202312312350_13   taglitac/adsl/1     tx
39  EFMTX;6591f046d8beb800016deaef   202312312344_9   thesitae/ptn3/1     tx
40    EFM;6591f199d4c961000177739d  202312312358_13         1btsts059    mob
41    EFM;6591f19aba09b0000160c08d  202312312358_13         1btsts059    mob
42  EFMTX;6591ef19d7d6bc000194445c  202312312358_14   viarital/prhu/4     tx

[13123614 rows x 4 columns]

In [37]:
cluster_merge = pd.merge(cluster_filtered, total_alarms, on='alarm_id', how='left')

In [38]:
num_rows = cluster_merge['slogan'].isnull().sum()
num_rows

37

In [39]:
# Calcola il numero di valori univoci nella colonna 'slogan'
num_unique_values = cluster_merge['slogan'].nunique()

In [40]:
num_unique_values

119

In [41]:
# Conta il numero di volte che ogni valore unico nella colonna 'slogan' appare
slogan_counts = cluster_merge['slogan'].value_counts()

In [42]:
slogan_counts

slogan
base station connectivity problem                                                                                                                                                                                    2344815
cell logical channel availability supervision                                                                                                                                                                        1115193
apparato isolato                                                                                                                                                                                                      948541
base station connectivity degraded                                                                                                                                                                                    810588
signal degraded                                                                                                                                                                                                       785643
                                                                                                                                                                                                                      ...
cardinitcard initializing                                                                                                                                                                                                  1
vc unequipped ho vc unequipped                                                                                                                                                                                             1
switch unitpath signal label unequipped                                                                                                                                                                                    1
interfaccia                                                                                                                                                                                                                1
pm bip over the received signal attenuates too much the transmitting part of the opposite station failed the optical fiber end is unclean or the connector is incorrect the receiving part of this station failed          1
Name: count, Length: 119, dtype: int64

In [43]:
cluster_merge

,alarm_id,cluster_id2,ne_id,domain,slogan
0,EFM;63af9dfe2aaf2c000125807a,202301010000_1,1btste08d,mob,fermo parziale lte
1,EFM;63af9dfec623b40001a5c9cf,202301010000_1,1btste08d,mob,base station service problem
2,COS1P;136902468,202301010000_2,alesitaj/ad16/73,tx,NaN
3,EFM;63b0beaf2aaf2c0001258736,202301010000_3,5btsle119,mob,allarme trasmissivo ip
4,COS1P;136891403,202301010000_4,ancoitab/oadm/1,tx,apparato isolato
...,...,...,...,...,...
13123609,EFMTX;6591efb9d7d6bc00019444d8,202312312350_13,taglitac/adsl/1,tx,guasto ima
13123610,EFMTX;6591f046d8beb800016deaef,202312312344_9,thesitae/ptn3/1,tx,oamloc locv
13123611,EFM;6591f199d4c961000177739d,202312312358_13,1btsts059,mob,base station service problem
13123612,EFM;6591f19aba09b0000160c08d,202312312358_13,1btsts059,mob,fermo parziale lte
13123613,EFMTX;6591ef19d7d6bc000194445c,202312312358_14,viarital/prhu/4,tx,lof

In [44]:
clusters = cluster_merge.groupby(['cluster_id2'])

In [45]:
clusters_filtered = clusters.filter(lambda x: len(x) >= 3)

In [46]:
clusters_filtered

,alarm_id,cluster_id2,ne_id,domain,slogan
12,COS1P;136899249,202301010000_12,beneital/ad64/2,tx,apparato isolato
16,COS1P;136885076,202301010000_16,bracitah/ad16/1,tx,apparato isolato
17,COS1P;136885115,202301010000_16,bracitam/ad16/3,tx,apparato isolato
26,COS1P;136884642,202301010000_25,capoitam/adm4/1,tx,apparato isolato
27,COS1P;136884882,202301010000_25,capoitaq/ad16/1,tx,apparato isolato
...,...,...,...,...,...
13123605,EFM;6591ef405795e30001315adb,202312312352_14,1btsrm155,mob,fermo cella lte
13123606,EFMTX;6591ee0801021b00010facb4,202312312340_13,sassitbn/adsl/100,tx,fermo totale apparato
13123608,EFMTX;6591efb9d7d6bc00019444d6,202312312350_13,taglitac/adsl/1,tx,guasto ima
13123609,EFMTX;6591efb9d7d6bc00019444d8,202312312350_13,taglitac/adsl/1,tx,guasto ima
13123610,EFMTX;6591f046d8beb800016deaef,202312312344_9,thesitae/ptn3/1,tx,oamloc locv

In [47]:
clusters_filtered_grouped = clusters_filtered.groupby(["cluster_id2"])

In [48]:
clusters_filtered = clusters_filtered_grouped.filter(lambda x: x['ne_id'].nunique() >= 2)

In [49]:
clusters_filtered

,alarm_id,cluster_id2,ne_id,domain,slogan
16,COS1P;136885076,202301010000_16,bracitah/ad16/1,tx,apparato isolato
17,COS1P;136885115,202301010000_16,bracitam/ad16/3,tx,apparato isolato
26,COS1P;136884642,202301010000_25,capoitam/adm4/1,tx,apparato isolato
27,COS1P;136884882,202301010000_25,capoitaq/ad16/1,tx,apparato isolato
28,COS1P;136884883,202301010000_25,capoitaq/ad16/1,tx,apparato isolato
...,...,...,...,...,...
13123602,EFM;6591f07dadefac0001744e96,202312312354_7,7btsre15f,mob,base station connectivity problem
13123603,EFM;6591f08739628d00013784db,202312312354_7,7btsre0b9,mob,base station connectivity problem
13123604,EFM;6591f08cadefac0001744ea1,202312312354_7,7btsre04b,mob,base station connectivity problem
13123606,EFMTX;6591ee0801021b00010facb4,202312312340_13,sassitbn/adsl/100,tx,fermo totale apparato
13123610,EFMTX;6591f046d8beb800016deaef,202312312344_9,thesitae/ptn3/1,tx,oamloc locv

In [50]:
num_rows = clusters_filtered['slogan'].isnull().sum()
num_rows

11